import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { ThemeProvider } from '@/providers/theme-provider';
import QueryProvider from '@/providers/query-provider';
import { Toaster } from '@/components/ui/toaster';
import { dark, neobrutalism } from '@clerk/themes';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        signIn: {
          variables: {
            colorBackground: '#111827',
            colorPrimary: '#3b82f6',
            colorText: '#fcfcfc',
            colorInputBackground: '#3c3a5e',
            colorNeutral: '#9ca3af',
            colorInputText: '#fcfcfc',
            colorTextSecondary: '#9ca3af',
          },
        },
        signUp: {
          variables: {
            colorBackground: '#111827',
            colorPrimary: '#3b82f6',
            colorText: '#fcfcfc',
            colorInputBackground: '#3c3a5e',
            colorNeutral: '#9ca3af',
            colorInputText: '#fcfcfc',
            colorTextSecondary: '#9ca3af',
          },
        },
        userProfile: {
          // variables: {
          //   colorBackground: '#111827',
          //   colorPrimary: '#3b82f6',
          //   colorText: '#fcfcfc',
          //   colorInputBackground: '#3c3a5e',
          //   colorNeutral: '#9ca3af',
          //   colorInputText: '#fcfcfc',
          //   colorTextSecondary: '#9ca3af',
          // },
          baseTheme: dark,
        },
        userButton: {
          variables: {
            colorBackground: '#111827',
            colorPrimary: '#3b82f6',
            colorText: '#fcfcfc',
            colorInputBackground: '#3c3a5e',
            colorNeutral: '#9ca3af',
            colorInputText: '#fcfcfc',
            colorTextSecondary: '#9ca3af',
          },
        },
        organizationProfile: {
          variables: {
            colorBackground: '#111827',
            colorPrimary: '#3b82f6',
            colorText: '#fcfcfc',
            colorInputBackground: '#3c3a5e',
            colorNeutral: '#9ca3af',
            colorInputText: '#fcfcfc',
            colorTextSecondary: '#9ca3af',
          },
        },
      }}
      dynamic
    >
      <QueryProvider>
        <html lang='en' suppressHydrationWarning>
          <body className={`${poppins.className} antialiased`}>
            <ThemeProvider
              attribute='class'
              defaultTheme='system'
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
            <Toaster />
          </body>
        </html>
      </QueryProvider>
    </ClerkProvider>
  );
}
